### ISSUE TITLE
Styles on IE browser

### ISSUE THREAD

**Issue by jurahalas** [catamphetamine/react-phone-number-input#111]
![icons for country](https://user-images.githubusercontent.com/6998100/36665874-6e92737c-1af1-11e8-932e-e2d9de9599f5.JPG)

icons shows incorectly

**Comment by catamphetamine** [comment]
True, in IE 11 SVG icons don't show correctly for some reason.

**Comment by catamphetamine** [comment]
This project uses [http://flag-icon-css.lip.is/](http://flag-icon-css.lip.is/) SVG icons internally.
And I found this exact issue on stack overflow:
https://stackoverflow.com/questions/27970520/svg-with-width-height-doesnt-scale-on-ie9-10-11
The reason is that the flag icons don't specify `viewBox` property on `<svg/>` element.
There is an issue in the flag icons repo:
https://github.com/lipis/flag-icon-css/issues/110
But from the comments there it seems like setting `viewBox` breaks some of the flags.
So it's messed up.
And seems like they're not going to fix that.

**Comment by lipis** [comment]
don't we love IE?!

**Comment by catamphetamine** [comment]
@lipis Well, at least I found a workaround for this: placing the `<img/>` in a `<div/>` and setting `max-width: 100%` and `max-height: 100%` on the image, like you do it on your demo page.

**Comment by lipis** [comment]
If you are OK with workaround.. that's fine! Supporting IE11 is not really in our agenda..

**Comment by catamphetamine** [comment]
I wouldn't commit to spending my time for IE either.

**Comment by lipis** [comment]
Thank you!

**Comment by catamphetamine** [comment]
@jurahalas Released `react-phone-number-input@0.17.1` with the fix.
That also fixes `<Select/>` scrolling to the top of the page in IE.
