### ISSUE TITLE
redux is installed

### ISSUE THREAD

**Issue by brikou** [catamphetamine/react-phone-number-input#122]
By using `react-responsive-ui` we get `redux`. Do we need all of this?

BTW thank you for the lib

**Comment by catamphetamine** [comment]
`react-responsive-ui` is not using any `redux`.

**Comment by catamphetamine** [comment]
Ah, actually, yeah, `redux` is used in `react-dnd` for some reason.
It's their choice and there seems to be no alternative Drag'n'Drop solution for React.
Still, `redux` is not bundled because only `Select` is used.
https://github.com/catamphetamine/react-phone-number-input/blob/9c24753a8199dcf129888e31727d0e18dcd75097/source/Input.js#L7-L9
One can verify that using Webpack Visualizer
https://chrisbateman.github.io/webpack-visualizer/
Or Webpack Analyze
http://webpack.github.io/analyse/
