### ISSUE TITLE
ES6 imports with libphonenumber-js

### ISSUE THREAD

**Issue by Huulivoide** [catamphetamine/react-phone-number-input#184]
Currently if one wants to use react-phone-number-input and libphonenumber-js directly with ES6 imports one ends up with 2 copies libphonenumber-js in the bundle.

For example
```js
/* File A: DisplayPhoneNumber.jsx */
// Imports the requested ES6 version of libphonenumber-js
import { formatNumber } from 'libphonenumber-js'; 

/* File B: EnterPhoneNumber.jsx */
// Imports index.js 
// → modules/PhoneInputNativeDefaultMetadata.js 
// → modules/PhoneInputNative.js
// → modules/PhoneInput.js
// → modules/InputBasic.js
// → libphonenumber-js/custom.js (formatIncompletePhoneNumber() & parseIncompletePhoneNumber())
// → libphonenumber-js/build/* which is the non ES6 version. 
import PhoneInput from 'react-phone-number-input';
```

**Comment by catamphetamine** [comment]
Oh, I see, so ES6 import conflicts with the ES5 import.
I guess I'll have to create an ES6 custom export then.

**Comment by catamphetamine** [comment]
But, if I made some `libphonenumber-js/custom/es6` export then what would I do with it?
I wouldn't be able to just replace `libphonenumber-js/custom` with `libphonenumber-js/custom/es6` because that would break it for all other users who don't use ES6 syntax.
I guess there's no solution here.
I could re-export `libphonenumber-js` from `react-phone-number-input/libphonenumber`, for example.

```js
module.exports = require('libphonenumber-js/index.common.js')
```

Or another solution is to write 
```js
import { formatNumber } from 'libphonenumber-js/index.common.js'
```

**Comment by Huulivoide** [comment]
I was thinking something about the following lines could possibly work. Would be a breaking change tough.

In libphonenumber-js things could be handled this way.

```js
// No import metadata from './metadata.min.json'

import parseNumberCustom from './es6/parse'
// … And all of the other imports, including the ones that are curtrently not exported by the index.js.
// Like the formatIncompletePhoneNumber() & parseIncompletePhoneNumber()

let defaultMetadata = null;

export function setDefaultMetadata(metadata) {
	defaultMetadata = new Metadata(metadata);
}

export function getDefaultMetadata() { return defaultMetadata }

export function parseNumber()
{
	let params = arguments;
	if (defaultMetadata != null && !(params[params.length - 1] instanceof Metadata)) {
		params = Array.prototype.slice.call(arguments)
		params(defaultMetadata)
	}
	return parseNumberCustom.apply(this, params)
}

```

Then the end user would instead use library like.

```js
import phonenumberMetadata from 'libphonenumber-js/metadata.min.js';
import { setDefaultMetadata, formatNumber } from 'libphonenumbetr-js };

setDefaultMetadata(phonenumberMetadata);
// Then do something with the formatNumber and friends.
```

This way there would no longer be any need for the problematic custom.js file.

React-phone-number-input itself seems to already import the default metadata file manually and imports the custom.js because of that. With the change above, this component could just use the default index file instead.

**Comment by catamphetamine** [comment]
That's an interesting idea but that would require all users add an extra line of code of configuration and no one would like that.
Another idea would be to extract `libphonenumber-js/custom` into `libphonenumber-js-custom` with `main/module` set up for automatic ES5/ES6 resolving. And `libphonenumber-js` would then import `libphonenumber-js-custom` and it would resolve ES5/ES6 automatically.
But that would mean maintaining two packages instead of one: all readme would go to `libphonenumber-js` and all code would go to `libphonenumber-js-custom`. It just doesn't feel like a good architecture, though it would work and would resolve correctly.

**Comment by catamphetamine** [comment]
I used the `package.json` approach in sub-directories which seems to kinda work.
https://github.com/catamphetamine/libphonenumber-js#min-vs-max-vs-mobile-vs-core
Now `libphonenumber-js`'s "custom" code resides in its own `/core` directory and has both ES6 and CommonJS exports in it's own `package.json` file.

`react-phone-number-input` package has also been split into similar sub-packages.
`react-phone-number-input/libphonenumber` export is now deprecated.

I didn't check though.
I guess it works.
Closing.
