### ISSUE TITLE
IE custom country select styles

### ISSUE THREAD

**Issue by Subha** [catamphetamine/react-phone-number-input#235]
Hi,

1. Do you have any solution for the dropdown not showing up as expected in IE11. Is there any polyfill to support the css variables in IE?

Herewith attaching a snapshot of how my IE looks when i select the dropdown.

![image](https://user-images.githubusercontent.com/12513265/52883680-d0f31800-3139-11e9-9f11-0f1a1653a760.png)

Thank you
Anu

**Comment by catamphetamine** [comment]
Hi.
Here's a screenshot of the demo page in IE11.
As you can see, everything works in this case.

![image](https://user-images.githubusercontent.com/477167/52918729-58dc4c00-330b-11e9-852a-7b37e9ea9430.png)

I guess your issue is that you didn't read the warning.
https://github.com/catamphetamine/react-phone-number-input#custom-country-select
See there, it explains.

**Comment by Subha** [comment]
Thanks for pointing that for me. I will look at the autoprefixer.
