### ISSUE TITLE
Rename the `country` prop to `defaultCountry`?

### ISSUE THREAD

**Issue by TylerRick** [catamphetamine/react-phone-number-input#277]
I have an idea. :) I wonder if renaming the `country` prop to `defaultCountry` would make it clearer how the prop is used and prevent people from thinking they can **_directly control_** the selected country via the `country` prop.

It just occurred to me that the country portion of this component (in contrast to the phone value) behaves basically like an uncontrolled component. And since a `default` prefix is conventionally used for uncontrolled components, this might make its behavior more self-documenting.

Read, for example, https://reactjs.org/docs/uncontrolled-components.html#default-values:

> With an uncontrolled component, you often want React to specify the initial value, but leave subsequent updates uncontrolled. To handle this case, you can specify a `defaultValue` attribute instead of `value`.

Then maybe you wouldn't have to keep explaining to people (see #165, #138) how the supplied `country` is only used (as a default value) if the internal country state is not already set/initialized based on the supplied phone number (which you can think of as _overriding_ the default)...

**Comment by catamphetamine** [comment]
> and prevent people from thinking they can directly control the selected country via the country prop.

Yeah, I guess `defaultCountry` would be the better name for the property.
Still, it's a long name, and I don't think people should ever want to change it.
But I agree that some people might assume they could change it and the component could even handle such change but I didn't add such functionality intentionally to keep things simple.
The idea's good nontheless, thx.
I just don't feel like doing the change.

**Comment by catamphetamine** [comment]
@TylerRick I noticed your issues are usually detailed and descriptive ones. That's good practice. Closing such descriptive issues isn't so easy though because the author has invested the time into describing things. But you know you won't be doing this, no matter how they ask.

**Comment by TylerRick** [comment]
Thanks, @catamphetamine. I'm glad you at least appreciate the carefully constructed issues I submit, even if you can't or won't implement all the changes I suggest.

Personally I think you should make the change. But that's easy for me to say. :)

I understand it would be hard to introduce such a change after you have many users already using the current API. Still, there are ways to do so, if you ever change your mind. (Helpful deprecation warnings in current minor releases (2.4), and wait until you increment the major version number (3.0) to introduce the breaking change, changing the deprecation warning into a helpful error message.)

> Still, it's a long name, 

With respect to you, it is not. It is only 2 letters longer than `defaultValue` would be. `display​Initial​Value​As​Local​Number`, on the other hand, is a long name, but it's okay, because it's clear (whereas a shorter name for the same prop would likely be ambiguous). Clarity is more important than short. 

> But I agree that some people might assume they could change it

Exactly. It would be a logical conclusion to arrive it. (See #165, #138) 

_Unless_ a prop name has a `default` prefix or contain the word "initial", one _should_ in general be able to safely assume that changing that prop gives you rather direct control over something.

> and the component could even handle such change but I didn't add such functionality intentionally to keep things simple.

I understand.

**Comment by catamphetamine** [comment]
@TylerRick 

> Thanks, @catamphetamine. I'm glad you at least appreciate the carefully constructed issues I submit, even if you can't or won't implement all the changes I suggest.

Yeah, the thing I learnt is that the job of a developer is adding stuff in the beginning and not adding stuff later because the code starts resembling a Jenga tower and the less you add to it the more stable it's gonna be (a complete rewrite = reconstruction would be favorable for a large change).

I guess when you're young every major verison update is exciting: oh, let's look what they've got. As you get older it's more like: oh, what now, another major version update. So I tend just to keep it calm and carry on: don't touch it and you'll make everyone's life easier. If things work and the pay's good, just set it up once and be done with it.

> Personally I think you should make the change.

It could be a potential candidate for a "To do" item though.
I keep such a list usually at the top of CHANGELOG.
Like this:
https://raw.githubusercontent.com/catamphetamine/react-responsive-ui/master/CHANGELOG.md
It's so that when the next time I decide to bump the major version I come across that stuff and maybe do some of those things as well.

> I understand it would be hard to introduce such a change after you have many users already using the current API. Still, there are ways to do so, if you ever change your mind. (Helpful deprecation warnings in current minor releases (2.4), and wait until you increment the major version number (3.0) to introduce the breaking change, changing the deprecation warning into a helpful error message.)

The thing is I currently don't see any reason for `v3` in the forseeable future: the current version seems to work, no major flaws. Maybe `2.x` is the last one.

> `display​Initial​Value​As​Local​Number`

Ha ha, yeah, you got me there.

> Unless a prop name has a default prefix or contain the word "initial", one should in general be able to safely assume that changing that prop gives you rather direct control over something.

Yeah.
Well, it's not exactly "default" because setting `country` later on with an untouched input does change it.
So it's kind of a "grey area".

**Comment by catamphetamine** [comment]
Released version `3.x` that renamed `country` to `defaultCountry`, as you suggested.
