### ISSUE TITLE
Without country select, my custom number input fails.

### ISSUE THREAD

**Issue by linareyne** [catamphetamine/react-phone-number-input#292]
When I `import PhoneInput from 'react-phone-number-input/input'`, my custom input that I set with `customNumberInput` stops working and the input reverts to the standard DOM input. Any preferred way around this?

Works perfectly otherwise!

**Comment by catamphetamine** [comment]
@linareyne You mean, "without country select" doesn't support `customNumberInput` property?
Try `inputComponent`, as per the docs: https://github.com/catamphetamine/react-phone-number-input#without-country-select

**Comment by linareyne** [comment]
Doh! Dunno how I missed that, swear I'd re-read that section 10 times looking for that line. @_@

Thanks!

**Comment by catamphetamine** [comment]
@linareyne Cool )
I am myself regularly confused when I have to dive into the codebase. Who even wrote this? Oh, that was me...
Maybe I'll write a new phone input component in the some future, just for mobile phones, without country select, smaller and simpler, because this one honestly already started feeling too bloated for me.
Your audio software sounds cool by the way. Respect.
