### ISSUE TITLE
Issue on switching to International and back

### ISSUE THREAD

**Issue by sashakirichek** [catamphetamine/react-phone-number-input#295]
1. Go to demo page:
http://catamphetamine.github.io/react-phone-number-input/
2. Enter phone: 
![image](https://user-images.githubusercontent.com/12151738/68671780-c9da2880-0558-11ea-93ff-0496b4d0fb35.png)
3. Change to International:
![image](https://user-images.githubusercontent.com/12151738/68671817-ea09e780-0558-11ea-9513-ee5e5e26f2c1.png)
4. Change back to initial country:
![image](https://user-images.githubusercontent.com/12151738/68672357-17a36080-055a-11ea-8f05-f3bafcd26925.png)
Country code now baked in to local phone part and cannot be parsed.

Introduced after 2.3.18. Works fine on 2.3.18. Relevant to any country.

**Comment by catamphetamine** [comment]
Indeed.
Initially I thought: "Who'd even want such a feature".
But then I found a use case: suppose a person enters their phone number in international format but for some reason the country isn't autodetected. Such a person then thinks that he also needs to select his country and so they do that and then their phone number is screwed.
I guess I'll be reverting the change: https://github.com/catamphetamine/react-phone-number-input/commit/d49a7c844537266c0a37ec5f5d931f8f1df46eb1
The original change was proposed by @TylerRick in https://github.com/catamphetamine/react-phone-number-input/issues/273

"Let's say I don't realize that a country code is required, so I just start typing a phone number as it would normally be entered in my country (US), like 206-555-1234. But to my surprise, Egypt is selected as the country (it was parsed from the text field) and the value is formatted as +20 65 551234. If I as the user am paying close attention, this should clue me in to the fact that it did not interpret my number as a US number. But since it is formatted all strangely now, it may not be clear exactly how to fix the problem. I might try one of 2 things:

...

Or 2. Try to fix it by choosing a different country from the select (mouse)
Perhaps just as likely, I, the hapless user, notice that the flag is incorrect and click on it to discover the drop-down. Sure enough, I see that Egypt is selected. "That's not right! Let me fix that..."
So I choose United States from the list and ... wat? Now it says +1 655 512 34! What happened to the 206 area code that I entered? (And of course, to add insult to injury, if I start typing 20 after the +1, I'll run into the issue where only the 2 ends up where I want it and the 0 ends up at the end.)"

**Comment by catamphetamine** [comment]
Released `react-phone-number-input@2.5.0` with the fix: the phone number is now being preserved when the country being switched to has the same "country calling code" as the current international number; the phone number is cleared otherwise.
Updated the [demo](http://catamphetamine.github.io/react-phone-number-input/).
