### ISSUE TITLE
Phone Input without Country - `limitMaxLength` prop missing

### ISSUE THREAD

**Issue by AlexReff** [catamphetamine/react-phone-number-input#330]
limitMaxLength is missing from `"react-phone-number-input/input"`

I would submit a PR to fix but am unfamiliar with the source.

```
Warning: React does not recognize the `limitMaxLength` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `limitmaxlength` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in input (created by ForwardRef(Input))
    in ForwardRef(Input) (created by ForwardRef(InputSmart))
    in ForwardRef(InputSmart) (created by ForwardRef(PhoneInput))
    in ForwardRef(PhoneInput)
```

**Comment by catamphetamine** [comment]
While at first I did attempt to copy-paste the feature from the "with country select" component, soon I reconsidered.
So a developer wants to limit how much digits can a person enter.
Just limiting the max length doesn't seem right, because, first, it's confusing for a generic user ("Why doesn't it type when the keys are being hit. Is the website defunct."), and, second, if there's some kind of phone number max length validation then it should also validate the min length, otherwise that would be an inconsistent engineering approach. Validating min length would be possible via an `isPossiblePhoneNumber()` function and an on-screen message, and so should the max length check be implemented too. That's my verdict. Closing. I see the upvotes on the original comment. Still, they say: "majority is usually wrong".
