### ISSUE TITLE
Country code not getting appended in phone number.

### ISSUE THREAD

**Issue by hiteshchaudhari-tudip** [catamphetamine/react-phone-number-input#335]
When I select a country with country code of length more than 3, the country code is not getting appended in the phone number.

I checked the same with selecting 'US Virgin Islands' and 'Virgin Islands Britain'. I'm getting US as a selected country for both of these.

Country code for 'Virgin Islands Britain' is +1284. But the phone number is appended only with +1 which is code for US.

I'm using 3.0.5 version of this package.

Can you please take care of this issue ASAP?

**Comment by hiteshchaudhari-tudip** [comment]
So, this issue is fixed?

**Comment by catamphetamine** [comment]
On second thought, this "prepend default area code" feature won't be added, because when a user selects "British Virgin Islands" and inputs "2291234", then they see "(229) 123-4" which clearly indicates that they should input the complete phone number (with area code).
So, unless a user completely doesn't understand what they're doing, they'd input the complete phone number (with area code).
