### ISSUE TITLE
Do not consider 0 as undefined

### ISSUE THREAD

**Issue by lauterry** [catamphetamine/react-phone-number-input#338]
Hi

If the user enters 0 in the input, then the lib considers that the value is undefined which in my case is troublesome.

Let me explain my use case : 

Below is my input without any value : 

![Capture d’écran 2020-02-25 à 18 47 28](https://user-images.githubusercontent.com/1374238/75316446-aa47e100-5865-11ea-9e9a-d6ff3373c627.png)

Below is my input with a value : 

![Capture d’écran 2020-02-25 à 18 47 41](https://user-images.githubusercontent.com/1374238/75316554-f2ff9a00-5865-11ea-8cc1-ed89cf3db599.png)

When the user enter a value, the label "Téléphone mobile" is going smaller on top on the input.

The problem is when the user starts to enter a 0, then the label stays below the 0 : 

![Capture d’écran 2020-02-25 à 18 47 48](https://user-images.githubusercontent.com/1374238/75316637-280bec80-5866-11ea-8714-199602db850f.png)

FYI, i'm using Formik with react-phone-number-input

Is there a way to fix this issue ? Maybe consider 0 as a valid value and not undefined

Best regards

**Comment by catamphetamine** [comment]
Hi.
First of all, don't mix up this library with other stuff: if it's some kind of an interoperability issue then it's out of the scope of this library.
Second, `value` is `undefined` in the case you've described and that's correct because `0` is not a possible phone number.
So, your case is that you want to determine whether the input is empty.
That can be done by examining its `value`: pass `ref` to the component and then see `ref.value`, or something like that.
`ref` is "forwarded" to the input component.

**Comment by lauterry** [comment]
Hi @catamphetamine 

Thx for your fast answer.

Indeed, the solution was simple and was to call `setFieldTouched` on `PhoneInput` `onChange` prop.

Best regards
