### ISSUE TITLE
'Select All' not clearing the country selection

### ISSUE THREAD

**Issue by mta59066** [catamphetamine/react-phone-number-input#339]
When using the default entry method (the topmost on demo page), cleaning the input field with backspace clears the country selection as well, but selecting the input field with `cmd+a` (select-all) and then typing over it does not clear the country selection. 

Example use case is, start typing a phone number without country code, realize that a country code is needed when seeing the flag after few key strokes, backspacing the entry and typing again with country code works as expected, but `cmd+a` and typing the country code does not produce the same result just adding the new country code after the old one.

Not sure if it is possible to detect that the input field is empty just before the first keystroke.

**Comment by catamphetamine** [comment]
> but `cmd+a` and typing the country code does not produce the same result just adding the new country code after the old one.

If a country is selected, it won't be automatically de-selected unless there's a `+` at the start of a phone number.

**Comment by mta59066** [comment]
> If a country is selected, it won't be automatically de-selected unless there's a + at the start of a phone number.

It is though, if you delete the input with `backspace`, the country is de-selected and a new one is selected without a `+` at the start.

**Comment by catamphetamine** [comment]
@mta59066 The country is reset when a user erases the input, but only if it was an international number (with a `+`).

**Comment by catamphetamine** [comment]
@mta59066 Do you think the behavior is incorrect in some case?

**Comment by mta59066** [comment]
The example use case I mentioned in my original post happens without `+`. Focus on the input field, start typing, ohh it needs a country code, `backspace` and continue typing with country code (without `+`) works perfectly, `ctrl+a` and do the same works differently. 

Just a suggestion that the usual expectation for `backspace` whole previous input and typing, versus `ctrl+a` and typing the exact same input should result in the same outcome.

**Comment by catamphetamine** [comment]
Ah, I see what you mean.
So, for example, if I enter `1 213 2222222`, then it selects `US`.
Then, if a user selects all and hits Backspace, it resets the country.
But if a user selects all and starts typing without hitting backspace, then it doesn't reset the country.
The reason is that when a country is selected, any input is valid, but when a country is not selected, then only `+` input is valid, and that's why `+` is selected.
It doesn't "need" a `+`.
It only "needs" it if there hasn't been any country selected before.
Perhaps it should also reset country when there was an international number, and then user selects all and types a digit?
Maybe.
I'll reopen this for now.

**Comment by catamphetamine** [comment]
After thinking about this feature for a bit, I've concluded that resetting country when user's input changes from a number with a `+` to a number without a `+` wouldn't be a 100% correct user experience, because a user might want to input a phone number for the currently selected country in local format (without `+`).
Resetting the country does make sense when a user erases the number completely because this way there's a moment in time when the user sees that the country has been reset for an empty input, and so they'll understand why the digits they've started typing are prefixed with a `+`: because immediately before they start typing digits there would be no country selected.
In a scenario with "Select all" and start typing there's no such time frame in which the country flag is reset, so it wouldn't be intuitive if a users wants to input a local number.
