### ISSUE TITLE
(Feature) Always show `+{countryCallingCode}` in the text input

### ISSUE THREAD

**Issue by shirazz** [catamphetamine/react-phone-number-input#341]
Is there a way to set the current country code in the input once the county select is changed? I have seen a [discussion](https://github.com/catamphetamine/react-phone-number-input/issues/273) on this. But it seems like it's based on the **V2** version. I would like to know whether it is possible now in V3. If not can you please suggest something so that i can look into it and may be submit a PR.

**Comment by shirazz** [comment]
I am not sure whether we are on the same page. This is what i meant. I have the `<PhoneInput/>` component with value `+91 98955 12345`. Since the Country is India, the Indian flag will show up. When I change the Country, may be to UAE. Now the input value disappears.  Instead of this whole value being removed, I want the country code (+971) to be displayed in the input field so that users can type the rest of his number. If this doesn't makes sense, can you please share your thoughts on why it doesn't makes sense so that i can make a correct understanding.

**Comment by catamphetamine** [comment]
> I want the country code (+971) to be displayed in the input field so that users can type the rest of his number.

I see. It does make sense then, but this library doesn't provide such functionality.
You can use "without country select" component and implement a custom country select for such cases.

**Comment by shirazz** [comment]
[Based on the code comment reference here](https://github.com/catamphetamine/react-phone-number-input/blob/master/source/PhoneInputWithCountry.js#L91)

![image](https://user-images.githubusercontent.com/1519700/75613780-1880f200-5b4b-11ea-9ba1-2f13f9e5b707.png) 

> The reason is that there's no way of finding out in which form should `value` be displayed: international or national.

Does a prop to set a format helps here. So while configuring the `<PhoneInput/>` component, the developer can decide on whether to show the value in national or international format. I am not sure whether i am going the wrong way. I think what i have requested will surely improve the UX and avoid some unwanted confusions.

**Comment by shirazz** [comment]
[Based on the code comment reference here](https://github.com/catamphetamine/react-phone-number-input/blob/master/source/PhoneInputWithCountry.js#L91)

![image](https://user-images.githubusercontent.com/1519700/75613780-1880f200-5b4b-11ea-9ba1-2f13f9e5b707.png) 

> The reason is that there's no way of finding out in which form should `value` be displayed: international or national.

I think what I have requested will surely improve the UX and avoid some confusions.  Does a prop to set a format helps here. So while configuring the `<PhoneInput/>` component, the developer can decide on whether to show the value in national or international format. I am not sure whether i am going the wrong way.

**Comment by catamphetamine** [comment]
> Does a prop to set a format helps here. So while configuring the <PhoneInput/> component, the developer can decide on whether to show the value in national or international format. I am not sure whether i am going the wrong way. I think what i have requested will surely improve the UX and avoid some unwanted confusions.

For that purpose, a "without country select" component is exported: it can be used to implement any degree of customization.

There could be a feature to always require international phone number input format on the "with country select" component (show country calling code initially and on `country` property change, also force prepend country calling code when entering digits without `+`), but I won't be implementing it because my opinion is that it's redundant.

**Comment by catamphetamine** [comment]
To formalize the "force international" feature specs:

* Initially, if there's no `value`
i. if `country` is set, then `parsedInput` should be `+{countryCallingCode}`.
ii. If `country` is not set, then `parsedInput` should be empty.

* Initially, if there is a `value`, then `parsedInput` should be `value`.

* If `country` property changes

i. If `parsedInput` is empty or equal to `+{getCountryCallingCode(this.state.country)}`, then automatically select the new `country` and set `parsedInput` to `+{getCountryCallingCode(newCountry)}`.

* If a user selects a country, then select the new country (change the flag, set `this.state.country`), and

i. If `parsedInput` is empty, then set `parsedInput` to `+{getCountryCallingCode(newCountry)}`.
ii. If `parsedInput`'s country calling code part is the same as for the new `country`, then leave `parsedInput` as is.
iii. If `parsedInput`'s country calling code part is not the same as for the new `country`, then set `parsedInput` to `+{getCountryCallingCode(newCountry)}`.

But, there're several unobvious cases:

* When a user erases the `+{getCountryCallingCode(country)}` via `Backspace`, will they be able to do so? If yes, then what happens when the user enters a digit after that? Should a `+` be automatically prepended?

* When "International" option is selected and there's no `value`, should the input text be `+`, or should it be empty? It would be logical if the input text was `+` but in that case the `placeholder` wouldn't be visible, and showing a `placeholder` is required in many apps that don't have a `label` above the input field.

* When there's a country selected, and the user selects all and inputs a digit, what should happen? Should a `+` be automatically prepended, or should `+{getCountryCallingCode(country)}` be automatically prepended, or should the number digits be input in national format instead? If the national format is used for the digits, then it would be insonsistent with the whole "international only" behavior. If `+` is prepended, then it would be non-intutitive, because a person might have expected `+{getCountryCallingCode(country)}` be prepended. If `+{getCountryCallingCode(country)}` is prepended, then it would be non-intutitive, because a person might have expected `+` be prepended. 

So, the conclusion is that the "only international format" behavior wouldn't be consistent.
This issue will be open so that other people could read the rationale on why it's not implemented.

I've pushed the code I've expermented with to a `feature/international` branch:
https://github.com/catamphetamine/react-phone-number-input/tree/feature/international

**Comment by shirazz** [comment]
@catamphetamine Thanks a lot!!! I never expected something like this. Hats off... 

> When a user erases the +{getCountryCallingCode(country)} via Backspace, will they be able to do so? If yes, then what happens when the user enters a digit after that? Should a + be automatically prepended?

**Yes,** We should allow the user to remove the input value via backspace. When user starts to type and if the country is not selected, since it is an international format we have to prepend a `+`. The only thing here to check is if his first input is already a `+` we shouldn't add one from our side.

> When "International" option is selected and there's no value, should the input text be +, or should it be empty? It would be logical if the input text was + but in that case the placeholder wouldn't be visible, and showing a placeholder is required in many apps that don't have a label above the input field.

We should never add a `+` in case if the input is empty. A `+` make sense only if we try to input a value. 

> When there's a country selected, and the user selects all and inputs a digit, what should happen?

In this case also a `+` should be prepended.  This will make sure the force international feature behaves the same in all the scenario. 

> https://github.com/catamphetamine/react-phone-number-input/tree/feature/international

Haven't got a chance to check this. I will check this and share my thoughts later today.

**Comment by catamphetamine** [comment]
@shirazz 

> Yes, We should allow the user to remove the input value via backspace. When user starts to type and if the country is not selected, since it is an international format we have to prepend a `+`. The only thing here to check is if his first input is already a `+` we shouldn't add one from our side.

Well, ok, that does kinda make sense.

> We should never add a `+` in case if the input is empty. A `+` make sense only if we try to input a value.

Ok, that does kinda make sense too. This way `placeholder` isn't discarded.

> When there's a country selected, and the user selects all and inputs a digit, what should happen? In this case also a `+` should be prepended. This will make sure the force international feature behaves the same in all the scenario.

So, if `US` is selected, and the user selects all and then presses `7` then the input value should be `+7` and the country should be reset to "International"? Well, maybe...

> Haven't got a chance to check this. I will check this and share my thoughts later today.

You don't need to.
I posted the link to the branch so that the code is not lost.
Now that we've seemingly sorted out the edge cases outlined above, maybe I will release this feature after all. We'll see.

**Comment by shirazz** [comment]
> So, if US is selected, and the user selects all and then presses 7 then the input value should be +7 and the country should be reset to "International"? Well, maybe...
Yea. i would suggest to change the country as well. 

>Now that we've seemingly sorted out the edge cases outlined above, maybe I will release this feature after all. We'll see.

Yea 👍. Waiting for the new release. I can also help to fix or report issues if i come across anything. Thank you @catamphetamine.

**Comment by catamphetamine** [comment]
@shirazz Published `react-phone-number-input@3.0.20` with `international` property.
Updated the demo.

**Comment by shirazz** [comment]
Tried the new version. The new feature is awesome. Thanks @catamphetamine

**Comment by shirazz** [comment]
Hi Nikolay,

The phone number input library is down :( can you please fix it?

Thanks
FRONTEND DEVELOPER
Shiraz Samad
shirazwaits@gmail.com
shirazsamad  Skype


Linkedin :  Shirazsamad
Twitter    :  Shirazz
Facebok  :  Shiraz.samad
Mobile     :  971-569240260
