### ISSUE TITLE
Having to select country twice

### ISSUE THREAD

**Issue by robbileifss** [catamphetamine/react-phone-number-input#347]
Hi,

I have an issue, maybe it's something I've missed or wrongly setup. But I can't find out.
When going back in my application to the page where I selected the country from the phoneinput control. Wanting to change the country, I have to select it twice in order for it to stick. See the attached gif.

![phoniinput](https://user-images.githubusercontent.com/10154861/77310659-970a2300-6cf6-11ea-9e43-0816cae009e7.gif)

**Comment by robbileifss** [comment]
@catamphetamine any idea if this is the framework or just my code?

**Comment by catamphetamine** [comment]
@robbileifss Hi.
Yeah, I haven't looked into the issue yet.
I can look at it some time later, but not anytime soon.
Maybe in a month or two.

**Comment by arikimolloy** [comment]
@robbileifss I was seeing the same issue.

This is what my code looked like:
`<PhoneInput value={value == null ? "" : `${value.rawInput}`} .......`

The fix for me was to instead of setting value to an empty string, set it to `"undefined"`:
`<PhoneInput value={value == null ? "undefined" : `${value.rawInput}`} ......`

**Comment by catamphetamine** [comment]
I'll add this note in the README since people are periodically expecting it to handle empty strings.

> Note: Don't pass an empty string `value`, pass `undefined` instead. Same's true for the `value` argument of `onChange` — when `value` is empty, it is `undefined`, not an empty string.
