### ISSUE TITLE
Missing CSS variable `PhoneInputCountrySelectArrow-height`

### ISSUE THREAD

**Issue by laclance** [catamphetamine/react-phone-number-input#362]
style.css line 9: 
```
--PhoneInputCountrySelectArrow-marginTop: calc(var(--PhoneInputCountrySelectArrow-height) / 2);
```
but `PhoneInputCountrySelectArrow-height` does not exist?

**Comment by catamphetamine** [comment]
Indeed, it wasn't defined.
This is equal to the CSS variable being ignored, so `margin-top` is actually ignored.
I removed the `--PhoneInputCountrySelectArrow-marginTop` variable from CSS, and the corresponding `margin-top` rule on the arrow element.
There's no need to release a new version with the fix because of how CSS variables work: when a CSS variable is not found, the CSS rule is ignored.
