### ISSUE TITLE
phone number is not beign formated properly

### ISSUE THREAD

**Issue by Talha8598** [catamphetamine/react-phone-number-input#395]
if i use normal phone number then it works fine but if i repeat the country code if accepts number greater then specified in limitMaxLength, as you can see below it is giving three different results for three different input formats

![image](https://user-images.githubusercontent.com/92149364/144821015-4f62f700-f319-4f2d-9c24-d3c9f78259c1.png)

![image](https://user-images.githubusercontent.com/92149364/144821385-57454664-61d1-43e8-aee7-5c7e328a52e4.png)

![image](https://user-images.githubusercontent.com/92149364/144821422-c5444d43-946f-4d66-a54e-03bb874cc634.png)

Code:

<PhoneInput
                placeholder="Enter phone number"
                value={"0900786012131312"}
                defaultCountry={"US"}
                limitMaxLength={true}
                onChange={(newVal)=>console.log(newVal)}
              />

**Comment by catamphetamine** [comment]
I've figured out why does it parse text `"1 111 111 1111 1"` as a national "significant" number `"+1 111 111 1111"`.

As soon as the user has input `"11"`, no `format` matches those "national number" digits in the `"US"` country metadata. Since no `format` matches, the number doesn't seem like a valid one, so it attempts to see if the user "forgot" to input a `"+"` at the start. And it looks like they might've to. So it acts as if the leading `"+"` is there, as if the user's input is `"+11"`. See `AsYouType.fixMissingPlus()` function.

So, since national "significant" number `"+1 111 111 1111"`, the `limitMaxLength` feature is working as expected.

**Comment by catamphetamine** [comment]
`limitMaxLength` operates on national "significant" number, not on the user's input.
