### ISSUE TITLE
Bug - international dialling code prefixed when current number starts with zero

### ISSUE THREAD

**Issue by jonathanchrisp** [catamphetamine/react-phone-number-input#55]
## Overview

If you are entering a local number starting with `zero` and then tab away from the field the current functionality adds the international dialling code to the input. Please see the example below using Australia.

![rfsnmjap8f](https://user-images.githubusercontent.com/406799/28510783-8e46dab4-708d-11e7-8dbf-5eecf731a22b.gif)

**Comment by jonathanchrisp** [comment]
Just to note this appears to have been introduced following the latest release, please see the [sandbox](https://codesandbox.io/s/Q1q18G81Z).

**Comment by catamphetamine** [comment]
Thx, the bug is confirmed and has been fixed in the latest release.
https://codesandbox.io/s/E9EEVgA0v

There can still be a bit of controversy regarding the `0` input – currently it parses as `undefined` and therefore the error message is not shown in your example.
But, it's extremely unlikely that any sane person would enter just `0` as their phone number so my point of view is that it's not a bug.
