### ISSUE TITLE
Bug - international dialling code now included in input field

### ISSUE THREAD

**Issue by jonathanchrisp** [catamphetamine/react-phone-number-input#58]
## Overview 
Following the latest deployment, the international dialling code now gets set in the input if passed in as an initial value. For example: 

![screen shot 2017-07-25 at 4 11 21 pm](https://user-images.githubusercontent.com/406799/28558158-ef12627a-7153-11e7-80ee-fd804afd96f0.png)

Is this an intended change? I didn't think the international dialling code should be displayed. You can see this issue in the following sandbox: https://codesandbox.io/s/E9EEVgA0v

**Comment by jonathanchrisp** [comment]
This only happens on initial load, I'm unable to replicate this when changing focus, changing country etc.

**Comment by catamphetamine** [comment]
Yeah, that's true, `convertToNational` seems to have malfunctioned due to the recent changes.
I made it working again, in the latest `patch` version: `react-phone-number-input@0.11.18`.

This new behaviour though got me thinking: this library should actually set `convertToNational` to `false` by default.
The reason is that the newer generation grows up when there are no stationary phones and therefore everyone inputs phone numbers with a `+` in their smartphones so local phone number should be now considered obsolete.
Therefore, the new version `react-phone-number-input@0.12` changes the default value of `convertToNational` property from `true` to `false`.

**Comment by jonathanchrisp** [comment]
Hey @catamphetamine, thanks for the quick turn around on all the issues I've raised over the last few days, appreciate your efforts here. I'll test out the newer versions 👍

**Comment by catamphetamine** [comment]
@jonathanchrisp Yeah, for a quick fix there must first exist a good bug report ideally accompanied with a live demo, like in your case. Not much bug reporters are capable of doing that.
