### ISSUE TITLE
Android issue with input of type "tel"

### ISSUE THREAD

**Issue by Fleezey** [catamphetamine/react-phone-number-input#59]
I found an issue using this component with any Samsung devices. The problem I encountered is that when I start typing values, it adds them but doesn't move the caret position.

Let's say i have this mask (___) ___-____
Expected results: (123) 456-7890
What I get: (234) 789-065

This happens only when the input is of type "tel" and when I'm using the default keyboard. I tried with GBoard and everything worked fine.

It would be great if we could have the type of the input as props. This way I could change the type back to "text" only for android devices, until a proper solution is found.

**Comment by catamphetamine** [comment]
Hmm, so you seem to have found the cause of this issue
https://github.com/catamphetamine/input-format/issues/2
@zimenskiy

Removing `type="tel"` disables phone number autocomplete feature.
Still, leaving `type="tel"` disables Samsung users from getting a good user experience.
What should we do...
I guess Samsung gets away with this, for now, so I'm removing `type="tel"` in the latest release, but it's not a just solution because semantics pays for what Samsung wasn't able to do right.
Whatever.
Try the new version of the package.

**Comment by Fleezey** [comment]
I was thinking that "type" could be passed as props so on our side we can decide if we want "text" or "tel". I know this is not a clean solution but it would be a good workaround so only android users would lose the autocomplete feature. Anyway, just a thought.

I'll give the new version a try as soon as possible.

Thanks!

**Comment by catamphetamine** [comment]
> I was thinking that "type" could be passed as props

It can
