### ISSUE TITLE
findDOMNode brings whole react-dom to the chunk

### ISSUE THREAD

**Issue by stereobooster** [catamphetamine/react-phone-number-input#98]
say you have like this

```js
import Loadable from "react-loadable";
const PhoneAsync = Loadable({
  loader: () => import("react-phone-number-input"),
  loading: () => <span>Loading the phone number</span>
});
```

this will produce a separate chunk (I'm talking about webpack2+, like c-r-a setup). This chunk will look like this

<img width="1269" alt="screen shot 2018-01-09 at 11 02 30" src="https://user-images.githubusercontent.com/179534/34715356-a2a08a0e-f52c-11e7-8d03-a4408a18e6b0.png">

Same issue in https://github.com/catamphetamine/input-format

**Comment by catamphetamine** [comment]
How are you going to use React in a web browser without `react-dom`?
It gets bundled anyway.
The only question is: why did your bundler include it the second time in this separate chunk because it must be in your main chunk already.

As for `input-format`, `react-dom` dependency there is isolated in a separate module and is therefore not an issue because in theory it gets tree-shaken if a bundler is smart enough to do that (or maybe there are some kind of "pure" annotations - the industry hasn't come up with a standard yet).
https://github.com/catamphetamine/input-format/blob/master/index.es6.js

**Comment by stereobooster** [comment]
> How are you going to use React in a web browser without react-dom?

Yes I will use in my application. I'm saying component should not depend on it.

> The only question is: why did your bundler include it the second time in this separate chunk because it must be in your main chunk already.

Because webpack cannot do magic. You asked for it it gets it for you. Tree shaking is very limited - you can use https://www.npmjs.com/package/eslint-plugin-tree-shaking to see what won't be tree shaken.

**Comment by catamphetamine** [comment]
> I'm saying component should not depend on it.

Why shouldn't it

> Because webpack cannot do magic.

It's not magic, these are very trivial and simple things, and if Webpack doesn't want to do them then it shouldn't be blamed on a library developer.

**Comment by stereobooster** [comment]
> these are very trivial and simple things

I suppose you have extensive experience in implementing tree shaking and bundlers. I will not bother you with my comments anymore.

**Comment by catamphetamine** [comment]
> I suppose you have extensive experience in implementing tree shaking and bundlers. I will not bother you with my comments anymore.

You surely won't, dick.

**Comment by catamphetamine** [comment]
Removed `ReactDOM` dependency in the latest version.
But it's still a required dependency when using React in a browser.
